function image_list = read_list(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Bo\Desktop\resized\retargetme\retarget.txt
%
% To extend the code to different selected data or a different text file,

% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/06 16:03:55

%% Initialize variables.
% filename = 'C:\Users\Bo\Desktop\resized\retargetme\retarget.txt';
delimiter = '';

%% Format string for each line of text:
%   column1: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
image_list = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;